CREATE TABLE IF NOT EXISTS userInterests (
	`id` INT AUTO_INCREMENT PRIMARY KEY,
    `USER_ID` INT,
    `USER_INPUT` VARCHAR(200),
    CONSTRAINT userInterestsFK FOREIGN KEY(USER_ID) REFERENCES users(id)
);